import { Agent, Project, Task } from "./types"

export const mockAgents: Agent[] = [
  {
    id: "agent-001",
    name: "ARIA",
    role: "Senior Frontend Engineer",
    department: "Frontend Development",
    status: "active",
    currentTask: "Build Office View & Task Detail panel",
    currentProject: "Mission Control",
    tokensUsed: 42300,
    lastActive: new Date().toISOString(),
  },
  {
    id: "agent-002",
    name: "KODA",
    role: "Backend Architect",
    department: "Backend Development",
    status: "available",
    tokensUsed: 18700,
    lastActive: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: "agent-003",
    name: "VELA",
    role: "UI/UX Lead Designer",
    department: "UI/UX Design",
    status: "available",
    tokensUsed: 12400,
    lastActive: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "agent-004",
    name: "NEXUS",
    role: "Research Analyst",
    department: "Research & Innovation",
    status: "idle",
    tokensUsed: 5200,
    lastActive: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "agent-005",
    name: "PULSE",
    role: "QA Engineer",
    department: "QA & Testing",
    status: "active",
    currentTask: "Run test suite & verify all 14 tests pass",
    currentProject: "Mission Control",
    tokensUsed: 18900,
    lastActive: new Date().toISOString(),
  },
  {
    id: "agent-006",
    name: "FORGE",
    role: "DevOps Engineer",
    department: "DevOps & Infrastructure",
    status: "active",
    currentTask: "Configure PM2 for 24/7 uptime",
    currentProject: "Mission Control",
    tokensUsed: 33600,
    lastActive: new Date().toISOString(),
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-001",
    title: "Mission Control dashboard — core layout",
    description: "Build the main dashboard with sidebar, stats bar, departments, agent roster and task feed.",
    department: "Frontend Development",
    assignedAgentId: "agent-001",
    status: "done",
    priority: "critical",
    projectId: "proj-001",
    isMvp: true,
    progress: 100,
    comments: [
      {
        id: "c-001",
        author: "ARIA",
        content: "Dashboard layout complete. Sidebar nav, stats bar, 3-column grid all working. Pushed to main.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        type: "update",
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "task-002",
    title: "Office View — virtual floor plan",
    description: "Visual representation of agents at desks, organized by department zones with live status glows.",
    department: "Frontend Development",
    assignedAgentId: "agent-001",
    status: "done",
    priority: "high",
    projectId: "proj-001",
    isMvp: true,
    progress: 100,
    comments: [
      {
        id: "c-002",
        author: "ARIA",
        content: "Office view built. 6 department zones, agent desks with glow effects, hover tooltips, click detail card.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        type: "update",
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "task-003",
    title: "Task Detail panel with comments",
    description: "Slide-in panel showing task progress, activity log, and ability to add notes/updates/blockers.",
    department: "Frontend Development",
    assignedAgentId: "agent-001",
    status: "done",
    priority: "critical",
    projectId: "proj-001",
    isMvp: true,
    progress: 100,
    comments: [
      {
        id: "c-003",
        author: "ARIA",
        content: "Task detail panel complete. Progress bar, comment types (note/update/blocker), Cmd+Enter to post.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        type: "update",
      },
      {
        id: "c-004",
        author: "JARVIS",
        content: "Solid work. This is the foundation for agent-to-agent communication on tasks.",
        createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        type: "note",
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "task-004",
    title: "PM2 — 24/7 uptime configuration",
    description: "Set up PM2 process manager with launchd so Mission Control runs on every reboot automatically.",
    department: "DevOps & Infrastructure",
    assignedAgentId: "agent-006",
    status: "done",
    priority: "high",
    projectId: "proj-001",
    isMvp: true,
    progress: 100,
    comments: [
      {
        id: "c-005",
        author: "FORGE",
        content: "PM2 configured. LaunchAgent plist written, startup script registered. Mission Control survives reboots.",
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        type: "update",
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "task-005",
    title: "Test suite — 14 passing tests",
    description: "Jest test suite covering mock data integrity, type conformance, agent/task/project validation.",
    department: "QA & Testing",
    assignedAgentId: "agent-005",
    status: "done",
    priority: "high",
    projectId: "proj-001",
    isMvp: true,
    progress: 100,
    comments: [
      {
        id: "c-006",
        author: "PULSE",
        content: "14/14 tests passing. Lint clean, build clean. Ready to connect real data.",
        createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        type: "update",
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "task-006",
    title: "Connect Mission Control to real GitHub data",
    description: "Replace mock projects/tasks with live data pulled from GitHub repos, issues, and PRs.",
    department: "Backend Development",
    status: "todo",
    priority: "critical",
    projectId: "proj-001",
    isMvp: true,
    progress: 0,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-007",
    title: "Connect OpenClaw gateway — live agent sessions",
    description: "Pull real agent session data from OpenClaw gateway API and map to agent statuses in real-time.",
    department: "Backend Development",
    status: "todo",
    priority: "critical",
    projectId: "proj-001",
    isMvp: true,
    progress: 0,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-008",
    title: "Remote access — expose Mission Control via Tailscale or tunnel",
    description: "Make Mission Control accessible from any device outside the local network.",
    department: "DevOps & Infrastructure",
    status: "todo",
    priority: "high",
    projectId: "proj-001",
    isMvp: false,
    progress: 0,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-009",
    title: "UI polish — animations, transitions, dark theme refinements",
    description: "Upgrade the visual design with smoother animations, better spacing, and refined color palette.",
    department: "UI/UX Design",
    status: "todo",
    priority: "medium",
    projectId: "proj-001",
    isMvp: false,
    progress: 0,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-010",
    title: "GitHub integration — push Mission Control repo",
    description: "Initialize git, connect to GitHub, push mission-control to christianbayona07/mission-control.",
    department: "DevOps & Infrastructure",
    assignedAgentId: "agent-006",
    status: "done",
    priority: "medium",
    projectId: "proj-001",
    isMvp: false,
    progress: 100,
    comments: [
      {
        id: "c-007",
        author: "FORGE",
        content: "Repo created at github.com/christianbayona07/mission-control. SSH configured, initial commit pushed.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        type: "update",
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
]

export const mockProjects: Project[] = [
  {
    id: "proj-001",
    name: "Mission Control",
    description: "AI agent operations dashboard — real-time visibility into agents, tasks, and projects",
    status: "active",
    tasks: mockTasks.filter((t) => t.projectId === "proj-001"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
]
